# Site settings
title: "al-Raqmiyyāt: Digital Islamic History"
header-img: images/loc_photos/a_cover.jpg

# - al-Dhahabī
# - Ta’rīkh al-islām

# Testing features
future:             true

# Owner/author information
name:               Maxim Romanov
author:             Maxim Romanov
bio:                Research fellow (PhD in Near Eastern Studies, U of Michigan, 2013) at the
                    Humboldt Chair for Digital Humanities [Institut für Informatik], University of Leipzig.
                    He studies Islamic historical texts with computational methods, currently focusing
                    on the analysis of multivolume biographical and bibliographical collections.
avatar:             RM_600.png
email:              romanov.maxim@gmail.com
description:        "Reading Traditional Sources with Nontraditional Methods"

permalink:          pretty
permalink:          /:year/:month-:day.html

share:              true
twitter_username:   maximromanov
github_username:    maximromanov
facebook_username:  maxim.romanov.925
disqus_shortname:   alraqmiyyat

email: romanov.maxim@gmail.com
description:
  "Reading Traditional Sources with Nontraditional Methods"
baseurl: ""
url: "http://maximromanov.github.io"

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-45427032-1

# Additional Gems
gems: [jekyll-paginate]

# Build settings
markdown:    kramdown
highlighter: rouge
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname


# Markdown Processors
#maruku:
#  use_tex:    false
#  use_divs:   false
#  png_engine: blahtex
#  png_dir:    images/latex
#  png_url:    /images/latex
#  fenced_code_blocks: true

#rdiscount:
#  extensions: []

#redcarpet:
#  extensions: ["footnotes", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data", "quote"] # "quote" for smart quotes

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style